// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Earmark$Type } from "./Earmark";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Earmark"]: Earmark$Type;
    ["contracts/Earmark.sol:Earmark"]: Earmark$Type;
  }

  interface ContractTypesMap {
    ["Earmark"]: GetContractReturnType<Earmark$Type["abi"]>;
    ["contracts/Earmark.sol:Earmark"]: GetContractReturnType<Earmark$Type["abi"]>;
  }
}
